# Generated by Django 5.2.5 on 2025-09-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("victorAiApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchat",
            name="user",
        ),
    ]
