# Generated by Django 5.2.5 on 2025-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victorAiApp", "0003_userchat_user_alter_aimemory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimemory",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
